article_index:
    path:     /
    defaults: { _controller: "BlogBundle:Article:index" }
    methods:  [GET , DELETE]

article_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:Article:show" }
    methods:  GET

article_new:
    path:     /new
    defaults: { _controller: "BlogBundle:Article:new" }
    methods:  [GET, POST]

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:Article:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:Article:delete" }
    methods:  DELETE

article_brouillon:
    path:     /brouillon
    defaults: { _controller: "BlogBundle:Article:new"}
    methods:  [GET, POST]


article_del:
    path:     /{id}
    defaults: { _controller: "BlogBundle:Article:deleteindex"}
    methods:  [GET , DELETE]