blog_article:
    resource: "@BlogBundle/Resources/config/routing/article.yml"
    prefix:   /article

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:list }
