blog_article:
    resource: "@BlogBundle/Resources/config/routing/article.yml"
    prefix:   /article

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:list }


single_article:
  path:      /{id}/single-article
  defaults: { _controller: BlogBundle:Article:showSingle }

add_comment:
    path:     /comment
    defaults: { _controller: BlogBundle:Commentaire:showComments }


edit_comment:
    path:     /{commentId}/{id}/edit/comment
    defaults: { _controller: BlogBundle:Commentaire:editComments }

delete_comment:
    path:     /{commentId}/{id}/delete/comment
    defaults: { _controller: BlogBundle:Commentaire:deleteComments }

like_comment:
    path:     /{commentId}/{id}/like/comment
    defaults: { _controller: BlogBundle:Commentaire:like }
